#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_successfactors_saf_framework_video_service_CaptureImage */

#ifndef _Included_com_successfactors_saf_framework_video_service_CaptureImage
#define _Included_com_successfactors_saf_framework_video_service_CaptureImage
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_successfactors_saf_framework_video_service_CaptureImage
	* Method:    start
	* Signature: (Ljava/lang/String;Ljava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_com_successfactors_saf_framework_video_service_CaptureImage_start
		(JNIEnv *, jobject, jstring, jstring);

	/*
	* Class:     com_successfactors_saf_framework_video_service_CaptureImage
	* Method:    stop
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_com_successfactors_saf_framework_video_service_CaptureImage_stop
		(JNIEnv *, jobject);

	char* JStr2CStrs(JNIEnv* env, jstring jstr);
#ifdef __cplusplus
}
#endif
#endif
