/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_natives_test_Test */

#ifndef _Included_com_natives_test_Test
#define _Included_com_natives_test_Test
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_natives_test_Test
	* Method:    hello
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_com_natives_test_Test_start
		(JNIEnv *, jobject, jstring, jstring);
	JNIEXPORT void JNICALL Java_com_natives_test_Test_stop
		(JNIEnv *, jobject);

	char* JStr2CStr(JNIEnv* env, jstring jstr);
#ifdef __cplusplus
}
#endif
#endif
